global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: '/spring-cloud-open-feign-metrics'
    metrics_path: '/spring-cloud-open-feign-metrics/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: [ 'host.docker.internal:8002' ]
        labels:
          app: 'spring-feign-client'