server:
  port: 8002
  servlet:
    context-path: /spring-cloud-open-feign-metrics

spring:
  application:
    name: spring-cloud-open-feign-metrics

logging:
  level:
    com.polovyi.ivan.client: DEBUG

feign:
  client:
    url: http://localhost:8001/spring-customer-app/v1/customers

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info
  metrics:
    tags:
      application: ${spring.application.name}
